from django.urls import path
from . import views

urlpatterns = [
    path ('', views.home, name = 'home'),
    
    #path('', views.index, name='index'),
    #     path('allbooks', views.allbooks, name='all'),
    path('searchbooks', views.searchbooks, name='search'),
    path('or', views.searchor, name='searchor'),
    path('avg', views.avg, name='avg'),
    # path('form', views.showForm, name='form'),
    # path('formone', views.showForm1, name='form1'),
    # path('initial', views.showFormInitial, name='initial'),
    path('all', views.all, name = 'filter'),
    path('search', views.search, name = 'againsearch'),
    path('searchbybook', views.searchbybook, name = 'Searchbybook'),
    path('inputsearchbybook', views.inputsearchbybook, name = 'SearchbyInput'),
    path('inputsearchbyprice', views.inputsearchbyprice, name = 'Inputsearchbyprice'),
    path ('between', views.between , name = "Between"),
    path ('allbooks', views.allbooks , name = "allbooks"),
    path ('base', views.base , name = "base"),
    path ('bootstrap', views.bootstrap , name = "bootstrap"),
    path ('project', views.project1 , name = "project"),
    path ('header', views.header , name = "header"),
    path ('quiz', views.quizhome , name = "quiz"),
    path ('quizpage', views.quizpage , name = "quizpage"),
    path ('session', views.session, name = "session"),
    path ('validation', views.validation, name = "validation"),
    path ('result', views.result, name = "result"),
    path ('testresult', views.testresult, name = "testresult"),
    path ('set', views.setcookies, name = "setcookies"),
    path ('get', views.getcookies, name = "getcookies"),
    path ('todohome', views.todohome),
    path ('todocreate', views.todocreate),
    path ('tododesign', views.tododesign),
    path('weather', views.weather, name = "weather"),
    path('weathercity', views.weathercity, name = "weathercity"),
    path('quiztf', views.quiztf, name = "quiztf"),
    path('tfquiz', views.tfquiz, name = "tfquiz"),
    path('apitest', views.apitest, name = "apitest"),
    path('sessionquiz', views.sessionquiz, name = "sessionquiz"),
    path('setsession', views.setsession, name = "setsession"),
    path('getsession', views.getsession, name = "getsession"),
    path('removesession', views.removesession, name = "removesession"),
    path('sessionset', views.sessionset, name = "sessionset"),
    path('sessionremove', views.sessionremove, name = "sessionremove"),
    path('sessionview', views.sessionview, name = "sessionview"),

]