# Generated by Django 3.2.13 on 2022-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('quiztitle', models.CharField(max_length=100)),
                ('quizimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
