# Generated by Django 3.2.13 on 2022-06-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('opta', models.CharField(max_length=200)),
                ('optb', models.CharField(max_length=200)),
                ('optc', models.CharField(max_length=200)),
                ('optd', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
                ('quizno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.quiz')),
            ],
        ),
    ]
