# Generated by Django 3.2.13 on 2022-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_result_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
