# Generated by Django 3.2.13 on 2022-06-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='TodoList',
        ),
    ]
